exports.home=(req,res)=>{
    res.render('home');
};
exports.about=(req,res)=>{
  res.render('about');  
};
exports.menu=(req,res)=>{
  res.render('menu');  
};
exports.contact=(req,res)=>{
  res.render('contact');  
};
exports.login=(req,res)=>{
    res.render('login');
};
exports.register=(req,res)=>{
    res.render('register');
};